using System.Collections.Generic;
using AutoClicker.Models;

namespace AutoClicker.Utils
{
    /// <summary>
    /// UI localization. Strings are keyed by their English source text
    /// (gettext-style): T("Always on top") returns the translation for the
    /// active language, or the English text itself when no translation exists, so
    /// any untranslated string degrades gracefully to English rather than breaking.
    ///
    /// All controls built through UiFactory pass their text through T automatically,
    /// so adding a translation here localizes it everywhere without touching call
    /// sites. Language changes apply on restart.
    /// </summary>
    public static class Localization
    {
        public static Language Current { get; set; } = Language.English;

        /// <summary>
        /// The .NET culture matching the current app language, used for formatting
        /// dates (weekday/month names) so charts and date labels follow the chosen
        /// language rather than the operating system locale.
        /// </summary>
        public static System.Globalization.CultureInfo DateCulture
        {
            get
            {
                try
                {
                    switch (Current)
                    {
                        case Language.Spanish: return System.Globalization.CultureInfo.GetCultureInfo("es");
                        case Language.French: return System.Globalization.CultureInfo.GetCultureInfo("fr");
                        case Language.German: return System.Globalization.CultureInfo.GetCultureInfo("de");
                        case Language.Italian: return System.Globalization.CultureInfo.GetCultureInfo("it");
                        case Language.Portuguese: return System.Globalization.CultureInfo.GetCultureInfo("pt");
                    }
                }
                catch { /* fall through to invariant if the culture isn't available */ }
                return System.Globalization.CultureInfo.InvariantCulture;
            }
        }

        public static IReadOnlyList<string> LanguageNames => new[]
        {
            "English", "Español", "Français", "Deutsch"
        };

        /// <summary>Returns the localized string for the English source text.</summary>
        public static string T(string english)
        {
            if (string.IsNullOrEmpty(english) || Current == Language.English)
            {
                return english;
            }

            Dictionary<string, string> table = TableFor(Current);
            if (table != null && table.TryGetValue(english, out string value))
            {
                return value;
            }

            return english; // graceful fallback
        }

        private static Dictionary<string, string> TableFor(Language language)
        {
            switch (language)
            {
                case Language.Spanish: return Es;
                case Language.French: return Fr;
                case Language.German: return De;
                case Language.Italian: return It;
                case Language.Portuguese: return Pt;
                default: return null;
            }
        }

        private static readonly Dictionary<string, string> Es = new Dictionary<string, string>
        {
            ["Clicker"] = "Clic",
            ["Multi-Point"] = "Multipunto",
            ["Macros"] = "Macros",
            ["Statistics"] = "Estadísticas",
            ["Keybinds"] = "Atajos",
            ["Settings"] = "Ajustes",
            ["Click Interval"] = "Intervalo de clic",
            ["Hours"] = "Horas", ["Minutes"] = "Minutos", ["Seconds"] = "Segundos", ["Millis"] = "Milis",
            ["Total delay between clicks. Minimum 1 ms."] = "Retraso total entre clics. Mínimo 1 ms.",
            ["Click Options"] = "Opciones de clic",
            ["Button"] = "Botón", ["Type"] = "Tipo", ["Mode"] = "Modo",
            ["Click Position"] = "Posición de clic",
            ["Current cursor position"] = "Posición actual del cursor",
            ["Fixed position"] = "Posición fija",
            ["Multi-point (see Multi-Point tab)"] = "Multipunto (ver pestaña Multipunto)",
            ["Restore cursor position when stopped"] = "Restaurar la posición del cursor al detener",
            ["Repeat"] = "Repetir",
            ["Until stopped"] = "Hasta detener", ["Fixed count:"] = "Cantidad fija:", ["For (seconds):"] = "Durante (segundos):",
            ["Burst Settings"] = "Ajustes de ráfaga", ["Clicks per burst"] = "Clics por ráfaga", ["Pause (ms)"] = "Pausa (ms)",
            ["Randomization (anti-pattern)"] = "Aleatorización (anti-patrón)",
            ["Randomize interval  ±"] = "Aleatorizar intervalo  ±", ["Randomize position  ±"] = "Aleatorizar posición  ±",
            ["Manual Speed"] = "Velocidad manual", ["Speed (10 = 1.0x)"] = "Velocidad (10 = 1.0x)",
            ["Anti-Freeze Protection"] = "Protección anticongelación",
            ["Enabled (prevents system freeze)"] = "Activado (evita que el sistema se congele)",
            ["Max CPS"] = "CPS máx.", ["CPU %"] = "CPU %", ["CPS Test"] = "Prueba de CPS",
            ["Pick…"] = "Elegir…", ["Profile:"] = "Perfil:",
            ["New"] = "Nuevo", ["Save"] = "Guardar",
            ["Quick Capture"] = "Captura rápida", ["Add…"] = "Añadir…", ["Edit…"] = "Editar…",
            ["Remove"] = "Quitar", ["Show on screen"] = "Mostrar en pantalla", ["Order:"] = "Orden:",
            ["Name:"] = "Nombre:", ["X"] = "X", ["Y"] = "Y",
            ["Saved macros"] = "Macros guardadas", ["Rename…"] = "Renombrar…", ["Duplicate"] = "Duplicar",
            ["Move Up"] = "Subir", ["Move Down"] = "Bajar", ["Export…"] = "Exportar…", ["Import…"] = "Importar…",
            ["Delete"] = "Eliminar", ["Notes…"] = "Notas…", ["Export all…"] = "Exportar todo…",
            ["Import all…"] = "Importar todo…", ["Merge"] = "Combinar", ["Merge…"] = "Combinar…",
            ["Record"] = "Grabar", ["● Record"] = "● Grabar", ["Playback"] = "Reproducción",
            ["Loops (0 = infinite)"] = "Bucles (0 = infinito)",
            ["Countdown (s, 0 = off)"] = "Cuenta atrás (s, 0 = no)", ["Loop delay (ms)"] = "Retraso entre bucles (ms)",
            ["▶ Play"] = "▶ Reproducir", ["Once"] = "Una vez", ["■ Stop"] = "■ Detener",
            ["Smooth mouse movement"] = "Movimiento suave del ratón", ["Ready."] = "Listo.",
            ["Live Monitor"] = "Monitor en vivo", ["Append to selected macro"] = "Añadir a la macro seleccionada",
            ["Capture keyboard"] = "Capturar teclado", ["Capture mouse movement"] = "Capturar movimiento del ratón",
            ["Not recording."] = "Sin grabar.", ["Clear All"] = "Borrar todo",
            ["Select, record, or play a macro to see steps here."] = "Selecciona, graba o reproduce una macro para ver los pasos aquí.",
            ["Live Dashboard"] = "Panel en vivo", ["Lifetime"] = "Histórico", ["Records"] = "Récords",
            ["Clicks by button"] = "Clics por botón",
            ["Session goal (clicks, 0 = off):"] = "Meta de sesión (clics, 0 = no):",
            ["Recent sessions (double-click for details, right-click for options)"] = "Sesiones recientes (doble clic para detalles, clic derecho para opciones)",
            ["Export CSV…"] = "Exportar CSV…", ["Reset session"] = "Reiniciar sesión",
            ["Reset lifetime"] = "Reiniciar histórico", ["Clear history"] = "Borrar historial",
            ["Action"] = "Acción", ["Hotkey"] = "Tecla", ["Toggle On/Off"] = "Activar/Desactivar",
            ["Save Keybinds"] = "Guardar atajos",
            ["Appearance"] = "Apariencia", ["Theme"] = "Tema", ["Always on top"] = "Siempre visible",
            ["Language"] = "Idioma", ["Use a custom accent colour"] = "Usar color de acento personalizado",
            ["Choose colour…"] = "Elegir color…", ["Preview"] = "Vista previa",
            ["Startup & Window"] = "Inicio y ventana",
            ["Launch Tempo when I sign in to Windows"] = "Iniciar Tempo al iniciar sesión en Windows",
            ["Hide window to tray when clicking starts"] = "Ocultar la ventana al empezar a hacer clic",
            ["Hotkeys are configured on the Keybinds tab."] = "Los atajos se configuran en la pestaña Atajos.",
            ["Behaviour"] = "Comportamiento",
            ["Minimise to tray instead of closing"] = "Minimizar a la bandeja en vez de cerrar",
            ["Start minimised to tray"] = "Iniciar minimizado en la bandeja",
            ["Show tray notifications"] = "Mostrar notificaciones de la bandeja",
            ["Confirm before exit while running"] = "Confirmar antes de salir si está en marcha",
            ["Allow Escape key as emergency stop"] = "Permitir Escape como parada de emergencia",
            ["Check for updates when Tempo starts"] = "Buscar actualizaciones al iniciar Tempo",
            ["Start delay before clicking (s):"] = "Retraso de inicio antes de hacer clic (s):",
            ["Interval step (ms) for increase/decrease:"] = "Paso del intervalo (ms) para aumentar/disminuir:",
            ["Data & Backup"] = "Datos y copia de seguridad", ["Open data folder"] = "Abrir carpeta de datos",
            ["Open log file"] = "Abrir archivo de registro", ["Export settings…"] = "Exportar ajustes…",
            ["Import settings…"] = "Importar ajustes…", ["Uninstall Tempo…"] = "Desinstalar Tempo…",
            ["Check for updates"] = "Buscar actualizaciones", ["About…"] = "Acerca de…",
            ["Reset to defaults"] = "Restablecer valores", ["Save Settings"] = "Guardar ajustes",
            ["▶  Start"] = "▶  Iniciar", ["■  Stop"] = "■  Detener",
            ["Copy summary"] = "Copiar resumen", ["Report a bug…"] = "Informar de un error…", ["Email a bug…"] = "Enviar un error por correo…",
            // Runtime status strings
            ["Running"] = "En marcha", ["Idle"] = "Inactivo", ["Paused"] = "Pausado",
            ["RUNNING"] = "EN MARCHA", ["IDLE"] = "INACTIVO", ["PAUSED"] = "PAUSADO",
            ["Playing macro"] = "Reproduciendo macro", ["Recording macro"] = "Grabando macro",
            ["Stopped (emergency)"] = "Detenido (emergencia)",
            ["Playing…"] = "Reproduciendo…", ["Playback cancelled."] = "Reproducción cancelada.",
            ["Nothing was recorded."] = "No se grabó nada.",
            ["Est. total: ∞ (looping)"] = "Total est.: ∞ (en bucle)", ["Est. total: ~"] = "Total est.: ~",
            ["Recording… bind/press the Record or Emergency-stop hotkey to finish."] = "Grabando… pulsa la tecla Grabar o Parada de emergencia para terminar.",
            ["Session goal reached"] = "Meta de sesión alcanzada", ["Checking…"] = "Comprobando…",
            ["Detection: off — no rate limit"] = "Detección: desactivada — sin límite",
            ["Profile: "] = "Perfil: ", ["Profile  •  "] = "Perfil  •  ",

            // --- Statistics tab (added 1.0.97) ---
            ["Session Clicks"] = "Clics de sesión",
            ["Total (Launch)"] = "Total (inicio)",
            ["Current CPS"] = "CPS actual",
            ["Peak CPS"] = "CPS máximo",
            ["Average CPS"] = "CPS promedio",
            ["Clicks / Min"] = "Clics / min",
            ["Elapsed"] = "Transcurrido",
            ["Today"] = "Hoy",
            ["Left"] = "Izquierdo",
            ["Right"] = "Derecho",
            ["Middle"] = "Central",
            ["Lifetime Clicks"] = "Clics totales",
            ["Sessions"] = "Sesiones",
            ["Best CPS Ever"] = "Mejor CPS histórico",
            ["Total Runtime"] = "Tiempo total",
            ["Most Clicks / Run"] = "Máx. clics / ejec.",
            ["Longest Run"] = "Ejecución más larga",
            ["Avg Clicks / Session"] = "Clics medios / sesión",
            ["Avg Run Length"] = "Duración media",
            ["This Week"] = "Esta semana",
            ["This Month"] = "Este mes",
            ["This Year"] = "Este año",
            ["Lifetime Avg CPS"] = "CPS medio total",
            ["Active Days"] = "Días activos",
            ["Best Day"] = "Mejor día",
            ["Busiest Weekday"] = "Día más activo",
            ["Busiest Hour"] = "Hora más activa",
            ["Top Profile"] = "Perfil principal",
            ["Current Streak"] = "Racha actual",
            ["Longest Streak"] = "Mejor racha",
            ["Daily Average"] = "Promedio diario",
            ["Insights"] = "Análisis",
            ["Unlock max speed (advanced)"] = "Desbloquear velocidad máxima (avanzado)",
            ["day"] = "día",
            ["days"] = "días",
            // --- Charts / status bar (1.0.98) ---
            ["Clicks per recent session"] = "Clics por sesión reciente",
            ["Clicks — last 7 days"] = "Clics — últimos 7 días",
            ["Clicks by hour of day"] = "Clics por hora del día",
            ["Clicks by day of week"] = "Clics por día de la semana",
            ["Last 7 days · {0} clicks · peak {1}"] = "Últimos 7 días · {0} clics · pico {1}",
            ["Loop"] = "Bucle",
            ["step"] = "paso",
            ["Clicks:"] = "Clics:",
            ["CPS:"] = "CPS:",
            ["Time:"] = "Tiempo:",
        };

        private static readonly Dictionary<string, string> Fr = new Dictionary<string, string>
        {
            ["Clicker"] = "Clic", ["Multi-Point"] = "Multi-point", ["Macros"] = "Macros",
            ["Statistics"] = "Statistiques", ["Keybinds"] = "Raccourcis", ["Settings"] = "Paramètres",
            ["Click Interval"] = "Intervalle de clic",
            ["Hours"] = "Heures", ["Minutes"] = "Minutes", ["Seconds"] = "Secondes", ["Millis"] = "Millis",
            ["Total delay between clicks. Minimum 1 ms."] = "Délai total entre les clics. Minimum 1 ms.",
            ["Click Options"] = "Options de clic", ["Button"] = "Bouton", ["Type"] = "Type", ["Mode"] = "Mode",
            ["Click Position"] = "Position du clic", ["Current cursor position"] = "Position actuelle du curseur",
            ["Fixed position"] = "Position fixe", ["Multi-point (see Multi-Point tab)"] = "Multi-point (voir l'onglet Multi-point)",
            ["Restore cursor position when stopped"] = "Restaurer la position du curseur à l'arrêt",
            ["Repeat"] = "Répéter", ["Until stopped"] = "Jusqu'à l'arrêt", ["Fixed count:"] = "Nombre fixe :",
            ["For (seconds):"] = "Pendant (secondes) :",
            ["Burst Settings"] = "Paramètres de rafale", ["Clicks per burst"] = "Clics par rafale", ["Pause (ms)"] = "Pause (ms)",
            ["Randomization (anti-pattern)"] = "Aléatoire (anti-motif)",
            ["Randomize interval  ±"] = "Intervalle aléatoire  ±", ["Randomize position  ±"] = "Position aléatoire  ±",
            ["Manual Speed"] = "Vitesse manuelle", ["Speed (10 = 1.0x)"] = "Vitesse (10 = 1.0x)",
            ["Anti-Freeze Protection"] = "Protection anti-gel",
            ["Enabled (prevents system freeze)"] = "Activé (évite le gel du système)",
            ["Max CPS"] = "CPS max", ["CPU %"] = "CPU %", ["CPS Test"] = "Test CPS",
            ["Pick…"] = "Choisir…", ["Profile:"] = "Profil :", ["New"] = "Nouveau", ["Save"] = "Enregistrer",
            ["Quick Capture"] = "Capture rapide", ["Add…"] = "Ajouter…", ["Edit…"] = "Modifier…",
            ["Remove"] = "Supprimer", ["Show on screen"] = "Afficher à l'écran", ["Order:"] = "Ordre :",
            ["Name:"] = "Nom :", ["X"] = "X", ["Y"] = "Y",
            ["Saved macros"] = "Macros enregistrées", ["Rename…"] = "Renommer…", ["Duplicate"] = "Dupliquer",
            ["Move Up"] = "Monter", ["Move Down"] = "Descendre", ["Export…"] = "Exporter…", ["Import…"] = "Importer…",
            ["Delete"] = "Supprimer", ["Notes…"] = "Notes…", ["Export all…"] = "Tout exporter…",
            ["Import all…"] = "Tout importer…", ["Merge"] = "Fusionner", ["Merge…"] = "Fusionner…",
            ["Record"] = "Enregistrer", ["● Record"] = "● Enregistrer", ["Playback"] = "Lecture",
            ["Loops (0 = infinite)"] = "Boucles (0 = infini)",
            ["Countdown (s, 0 = off)"] = "Compte à rebours (s, 0 = off)", ["Loop delay (ms)"] = "Délai entre boucles (ms)",
            ["▶ Play"] = "▶ Lire", ["Once"] = "Une fois", ["■ Stop"] = "■ Arrêter",
            ["Smooth mouse movement"] = "Mouvement fluide de la souris", ["Ready."] = "Prêt.",
            ["Live Monitor"] = "Moniteur en direct", ["Append to selected macro"] = "Ajouter à la macro sélectionnée",
            ["Capture keyboard"] = "Capturer le clavier", ["Capture mouse movement"] = "Capturer le mouvement de la souris",
            ["Not recording."] = "Pas d'enregistrement.", ["Clear All"] = "Tout effacer",
            ["Select, record, or play a macro to see steps here."] = "Sélectionnez, enregistrez ou lisez une macro pour voir les étapes ici.",
            ["Live Dashboard"] = "Tableau de bord en direct", ["Lifetime"] = "Cumul", ["Records"] = "Records",
            ["Clicks by button"] = "Clics par bouton",
            ["Session goal (clicks, 0 = off):"] = "Objectif de session (clics, 0 = off) :",
            ["Recent sessions (double-click for details, right-click for options)"] = "Sessions récentes (double-clic pour les détails, clic droit pour les options)",
            ["Export CSV…"] = "Exporter CSV…", ["Reset session"] = "Réinitialiser la session",
            ["Reset lifetime"] = "Réinitialiser le cumul", ["Clear history"] = "Effacer l'historique",
            ["Action"] = "Action", ["Hotkey"] = "Raccourci", ["Toggle On/Off"] = "Activer/Désactiver",
            ["Save Keybinds"] = "Enregistrer les raccourcis",
            ["Appearance"] = "Apparence", ["Theme"] = "Thème", ["Always on top"] = "Toujours au premier plan",
            ["Language"] = "Langue", ["Use a custom accent colour"] = "Couleur d'accent personnalisée",
            ["Choose colour…"] = "Choisir la couleur…", ["Preview"] = "Aperçu",
            ["Startup & Window"] = "Démarrage et fenêtre",
            ["Launch Tempo when I sign in to Windows"] = "Lancer Tempo à l'ouverture de session Windows",
            ["Hide window to tray when clicking starts"] = "Masquer la fenêtre lors du démarrage des clics",
            ["Hotkeys are configured on the Keybinds tab."] = "Les raccourcis se configurent dans l'onglet Raccourcis.",
            ["Behaviour"] = "Comportement",
            ["Minimise to tray instead of closing"] = "Réduire dans la barre au lieu de fermer",
            ["Start minimised to tray"] = "Démarrer réduit dans la barre",
            ["Show tray notifications"] = "Afficher les notifications",
            ["Confirm before exit while running"] = "Confirmer avant de quitter en cours d'exécution",
            ["Allow Escape key as emergency stop"] = "Autoriser Échap comme arrêt d'urgence",
            ["Check for updates when Tempo starts"] = "Vérifier les mises à jour au démarrage",
            ["Start delay before clicking (s):"] = "Délai avant de cliquer (s) :",
            ["Interval step (ms) for increase/decrease:"] = "Pas d'intervalle (ms) pour +/- :",
            ["Data & Backup"] = "Données et sauvegarde", ["Open data folder"] = "Ouvrir le dossier de données",
            ["Open log file"] = "Ouvrir le journal", ["Export settings…"] = "Exporter les paramètres…",
            ["Import settings…"] = "Importer les paramètres…", ["Uninstall Tempo…"] = "Désinstaller Tempo…",
            ["Check for updates"] = "Vérifier les mises à jour", ["About…"] = "À propos…",
            ["Reset to defaults"] = "Réinitialiser", ["Save Settings"] = "Enregistrer les paramètres",
            ["▶  Start"] = "▶  Démarrer", ["■  Stop"] = "■  Arrêter",
            ["Copy summary"] = "Copier le résumé", ["Report a bug…"] = "Signaler un bug…", ["Email a bug…"] = "Signaler un bug par e-mail…",
            // Runtime status strings
            ["Running"] = "En cours", ["Idle"] = "Inactif", ["Paused"] = "En pause",
            ["RUNNING"] = "EN COURS", ["IDLE"] = "INACTIF", ["PAUSED"] = "EN PAUSE",
            ["Playing macro"] = "Lecture de la macro", ["Recording macro"] = "Enregistrement de la macro",
            ["Stopped (emergency)"] = "Arrêté (urgence)",
            ["Playing…"] = "Lecture…", ["Playback cancelled."] = "Lecture annulée.",
            ["Nothing was recorded."] = "Rien n'a été enregistré.",
            ["Est. total: ∞ (looping)"] = "Total est. : ∞ (en boucle)", ["Est. total: ~"] = "Total est. : ~",
            ["Recording… bind/press the Record or Emergency-stop hotkey to finish."] = "Enregistrement… appuyez sur la touche Enregistrer ou Arrêt d'urgence pour terminer.",
            ["Session goal reached"] = "Objectif de session atteint", ["Checking…"] = "Vérification…",
            ["Detection: off — no rate limit"] = "Détection : désactivée — sans limite",
            ["Profile: "] = "Profil : ", ["Profile  •  "] = "Profil  •  ",

            // --- Statistics tab (added 1.0.97) ---
            ["Session Clicks"] = "Clics de session",
            ["Total (Launch)"] = "Total (lancement)",
            ["Current CPS"] = "CPS actuel",
            ["Peak CPS"] = "CPS max",
            ["Average CPS"] = "CPS moyen",
            ["Clicks / Min"] = "Clics / min",
            ["Elapsed"] = "Écoulé",
            ["Today"] = "Aujourd'hui",
            ["Left"] = "Gauche",
            ["Right"] = "Droit",
            ["Middle"] = "Milieu",
            ["Lifetime Clicks"] = "Clics à vie",
            ["Sessions"] = "Sessions",
            ["Best CPS Ever"] = "Meilleur CPS",
            ["Total Runtime"] = "Durée totale",
            ["Most Clicks / Run"] = "Max clics / session",
            ["Longest Run"] = "Plus longue session",
            ["Avg Clicks / Session"] = "Clics moy. / session",
            ["Avg Run Length"] = "Durée moyenne",
            ["This Week"] = "Cette semaine",
            ["This Month"] = "Ce mois",
            ["This Year"] = "Cette année",
            ["Lifetime Avg CPS"] = "CPS moyen total",
            ["Active Days"] = "Jours actifs",
            ["Best Day"] = "Meilleur jour",
            ["Busiest Weekday"] = "Jour le plus actif",
            ["Busiest Hour"] = "Heure la plus active",
            ["Top Profile"] = "Profil principal",
            ["Current Streak"] = "Série actuelle",
            ["Longest Streak"] = "Plus longue série",
            ["Daily Average"] = "Moyenne quotidienne",
            ["Insights"] = "Analyses",
            ["Unlock max speed (advanced)"] = "Débloquer la vitesse max (avancé)",
            ["day"] = "jour",
            ["days"] = "jours",
            // --- Charts / status bar (1.0.98) ---
            ["Clicks per recent session"] = "Clics par session récente",
            ["Clicks — last 7 days"] = "Clics — 7 derniers jours",
            ["Clicks by hour of day"] = "Clics par heure",
            ["Clicks by day of week"] = "Clics par jour de la semaine",
            ["Last 7 days · {0} clicks · peak {1}"] = "7 derniers jours · {0} clics · pic {1}",
            ["Loop"] = "Boucle",
            ["step"] = "étape",
            ["Clicks:"] = "Clics :",
            ["CPS:"] = "CPS :",
            ["Time:"] = "Temps :",
        };

        private static readonly Dictionary<string, string> De = new Dictionary<string, string>
        {
            ["Clicker"] = "Klicker", ["Multi-Point"] = "Mehrpunkt", ["Macros"] = "Makros",
            ["Statistics"] = "Statistiken", ["Keybinds"] = "Tastenkürzel", ["Settings"] = "Einstellungen",
            ["Click Interval"] = "Klickintervall",
            ["Hours"] = "Stunden", ["Minutes"] = "Minuten", ["Seconds"] = "Sekunden", ["Millis"] = "Millis",
            ["Total delay between clicks. Minimum 1 ms."] = "Gesamtverzögerung zwischen Klicks. Mindestens 1 ms.",
            ["Click Options"] = "Klickoptionen", ["Button"] = "Taste", ["Type"] = "Typ", ["Mode"] = "Modus",
            ["Click Position"] = "Klickposition", ["Current cursor position"] = "Aktuelle Cursorposition",
            ["Fixed position"] = "Feste Position", ["Multi-point (see Multi-Point tab)"] = "Mehrpunkt (siehe Mehrpunkt-Tab)",
            ["Restore cursor position when stopped"] = "Cursorposition beim Stoppen wiederherstellen",
            ["Repeat"] = "Wiederholen", ["Until stopped"] = "Bis gestoppt", ["Fixed count:"] = "Feste Anzahl:",
            ["For (seconds):"] = "Für (Sekunden):",
            ["Burst Settings"] = "Burst-Einstellungen", ["Clicks per burst"] = "Klicks pro Burst", ["Pause (ms)"] = "Pause (ms)",
            ["Randomization (anti-pattern)"] = "Zufall (Anti-Muster)",
            ["Randomize interval  ±"] = "Intervall zufällig  ±", ["Randomize position  ±"] = "Position zufällig  ±",
            ["Manual Speed"] = "Manuelle Geschwindigkeit", ["Speed (10 = 1.0x)"] = "Geschwindigkeit (10 = 1.0x)",
            ["Anti-Freeze Protection"] = "Einfrierschutz",
            ["Enabled (prevents system freeze)"] = "Aktiviert (verhindert Einfrieren)",
            ["Max CPS"] = "Max. CPS", ["CPU %"] = "CPU %", ["CPS Test"] = "CPS-Test",
            ["Pick…"] = "Wählen…", ["Profile:"] = "Profil:", ["New"] = "Neu", ["Save"] = "Speichern",
            ["Quick Capture"] = "Schnellerfassung", ["Add…"] = "Hinzufügen…", ["Edit…"] = "Bearbeiten…",
            ["Remove"] = "Entfernen", ["Show on screen"] = "Auf Bildschirm zeigen", ["Order:"] = "Reihenfolge:",
            ["Name:"] = "Name:", ["X"] = "X", ["Y"] = "Y",
            ["Saved macros"] = "Gespeicherte Makros", ["Rename…"] = "Umbenennen…", ["Duplicate"] = "Duplizieren",
            ["Move Up"] = "Nach oben", ["Move Down"] = "Nach unten", ["Export…"] = "Exportieren…", ["Import…"] = "Importieren…",
            ["Delete"] = "Löschen", ["Notes…"] = "Notizen…", ["Export all…"] = "Alle exportieren…",
            ["Import all…"] = "Alle importieren…", ["Merge"] = "Zusammenführen", ["Merge…"] = "Zusammenführen…",
            ["Record"] = "Aufnehmen", ["● Record"] = "● Aufnehmen", ["Playback"] = "Wiedergabe",
            ["Loops (0 = infinite)"] = "Schleifen (0 = unendlich)",
            ["Countdown (s, 0 = off)"] = "Countdown (s, 0 = aus)", ["Loop delay (ms)"] = "Schleifenverzögerung (ms)",
            ["▶ Play"] = "▶ Abspielen", ["Once"] = "Einmal", ["■ Stop"] = "■ Stopp",
            ["Smooth mouse movement"] = "Sanfte Mausbewegung", ["Ready."] = "Bereit.",
            ["Live Monitor"] = "Live-Monitor", ["Append to selected macro"] = "An ausgewähltes Makro anhängen",
            ["Capture keyboard"] = "Tastatur erfassen", ["Capture mouse movement"] = "Mausbewegung erfassen",
            ["Not recording."] = "Keine Aufnahme.", ["Clear All"] = "Alle löschen",
            ["Select, record, or play a macro to see steps here."] = "Makro auswählen, aufnehmen oder abspielen, um die Schritte hier zu sehen.",
            ["Live Dashboard"] = "Live-Übersicht", ["Lifetime"] = "Gesamt", ["Records"] = "Rekorde",
            ["Clicks by button"] = "Klicks nach Taste",
            ["Session goal (clicks, 0 = off):"] = "Sitzungsziel (Klicks, 0 = aus):",
            ["Recent sessions (double-click for details, right-click for options)"] = "Letzte Sitzungen (Doppelklick für Details, Rechtsklick für Optionen)",
            ["Export CSV…"] = "CSV exportieren…", ["Reset session"] = "Sitzung zurücksetzen",
            ["Reset lifetime"] = "Gesamt zurücksetzen", ["Clear history"] = "Verlauf löschen",
            ["Action"] = "Aktion", ["Hotkey"] = "Tastenkürzel", ["Toggle On/Off"] = "Ein/Aus",
            ["Save Keybinds"] = "Tastenkürzel speichern",
            ["Appearance"] = "Erscheinungsbild", ["Theme"] = "Design", ["Always on top"] = "Immer im Vordergrund",
            ["Language"] = "Sprache", ["Use a custom accent colour"] = "Eigene Akzentfarbe verwenden",
            ["Choose colour…"] = "Farbe wählen…", ["Preview"] = "Vorschau",
            ["Startup & Window"] = "Start & Fenster",
            ["Launch Tempo when I sign in to Windows"] = "Tempo bei der Windows-Anmeldung starten",
            ["Hide window to tray when clicking starts"] = "Fenster beim Klickstart in die Leiste verbergen",
            ["Hotkeys are configured on the Keybinds tab."] = "Tastenkürzel werden im Tab Tastenkürzel konfiguriert.",
            ["Behaviour"] = "Verhalten",
            ["Minimise to tray instead of closing"] = "In die Leiste minimieren statt schließen",
            ["Start minimised to tray"] = "Minimiert in der Leiste starten",
            ["Show tray notifications"] = "Infobereich-Benachrichtigungen anzeigen",
            ["Confirm before exit while running"] = "Vor dem Beenden während des Laufs bestätigen",
            ["Allow Escape key as emergency stop"] = "Esc-Taste als Not-Stopp erlauben",
            ["Check for updates when Tempo starts"] = "Beim Start nach Updates suchen",
            ["Start delay before clicking (s):"] = "Startverzögerung vor dem Klicken (s):",
            ["Interval step (ms) for increase/decrease:"] = "Intervallschritt (ms) für +/-:",
            ["Data & Backup"] = "Daten & Sicherung", ["Open data folder"] = "Datenordner öffnen",
            ["Open log file"] = "Protokolldatei öffnen", ["Export settings…"] = "Einstellungen exportieren…",
            ["Import settings…"] = "Einstellungen importieren…", ["Uninstall Tempo…"] = "Tempo deinstallieren…",
            ["Check for updates"] = "Nach Updates suchen", ["About…"] = "Über…",
            ["Reset to defaults"] = "Auf Standard zurücksetzen", ["Save Settings"] = "Einstellungen speichern",
            ["▶  Start"] = "▶  Start", ["■  Stop"] = "■  Stopp",
            ["Copy summary"] = "Zusammenfassung kopieren", ["Report a bug…"] = "Fehler melden…", ["Email a bug…"] = "Fehler per E-Mail melden…",
            // Runtime status strings
            ["Running"] = "Läuft", ["Idle"] = "Bereit", ["Paused"] = "Pausiert",
            ["RUNNING"] = "LÄUFT", ["IDLE"] = "BEREIT", ["PAUSED"] = "PAUSIERT",
            ["Playing macro"] = "Makro läuft", ["Recording macro"] = "Makro-Aufnahme",
            ["Stopped (emergency)"] = "Gestoppt (Notfall)",
            ["Playing…"] = "Wird abgespielt…", ["Playback cancelled."] = "Wiedergabe abgebrochen.",
            ["Nothing was recorded."] = "Es wurde nichts aufgenommen.",
            ["Est. total: ∞ (looping)"] = "Gesamt ca.: ∞ (Schleife)", ["Est. total: ~"] = "Gesamt ca.: ~",
            ["Recording… bind/press the Record or Emergency-stop hotkey to finish."] = "Aufnahme… drücke die Aufnahme- oder Not-Stopp-Taste zum Beenden.",
            ["Session goal reached"] = "Sitzungsziel erreicht", ["Checking…"] = "Wird geprüft…",
            ["Detection: off — no rate limit"] = "Erkennung: aus — kein Limit",
            ["Profile: "] = "Profil: ", ["Profile  •  "] = "Profil  •  ",

            // --- Statistics tab (added 1.0.97) ---
            ["Session Clicks"] = "Klicks (Sitzung)",
            ["Total (Launch)"] = "Gesamt (Start)",
            ["Current CPS"] = "Aktuelle CPS",
            ["Peak CPS"] = "Spitzen-CPS",
            ["Average CPS"] = "Durchschnittl. CPS",
            ["Clicks / Min"] = "Klicks / Min",
            ["Elapsed"] = "Verstrichen",
            ["Today"] = "Heute",
            ["Left"] = "Links",
            ["Right"] = "Rechts",
            ["Middle"] = "Mitte",
            ["Lifetime Clicks"] = "Klicks gesamt",
            ["Sessions"] = "Sitzungen",
            ["Best CPS Ever"] = "Beste CPS aller Zeiten",
            ["Total Runtime"] = "Gesamtlaufzeit",
            ["Most Clicks / Run"] = "Meiste Klicks / Lauf",
            ["Longest Run"] = "Längster Lauf",
            ["Avg Clicks / Session"] = "Ø Klicks / Sitzung",
            ["Avg Run Length"] = "Ø Lauflänge",
            ["This Week"] = "Diese Woche",
            ["This Month"] = "Dieser Monat",
            ["This Year"] = "Dieses Jahr",
            ["Lifetime Avg CPS"] = "Ø CPS gesamt",
            ["Active Days"] = "Aktive Tage",
            ["Best Day"] = "Bester Tag",
            ["Busiest Weekday"] = "Aktivster Wochentag",
            ["Busiest Hour"] = "Aktivste Stunde",
            ["Top Profile"] = "Top-Profil",
            ["Current Streak"] = "Aktuelle Serie",
            ["Longest Streak"] = "Längste Serie",
            ["Daily Average"] = "Tagesdurchschnitt",
            ["Insights"] = "Einblicke",
            ["Unlock max speed (advanced)"] = "Maximalgeschwindigkeit freischalten (erweitert)",
            ["day"] = "Tag",
            ["days"] = "Tage",
            // --- Charts / status bar (1.0.98) ---
            ["Clicks per recent session"] = "Klicks pro letzter Sitzung",
            ["Clicks — last 7 days"] = "Klicks — letzte 7 Tage",
            ["Clicks by hour of day"] = "Klicks nach Tagesstunde",
            ["Clicks by day of week"] = "Klicks nach Wochentag",
            ["Last 7 days · {0} clicks · peak {1}"] = "Letzte 7 Tage · {0} Klicks · Spitze {1}",
            ["Loop"] = "Schleife",
            ["step"] = "Schritt",
            ["Clicks:"] = "Klicks:",
            ["CPS:"] = "CPS:",
            ["Time:"] = "Zeit:",
        };

        private static readonly Dictionary<string, string> It = new Dictionary<string, string>
        {
            ["Clicker"] = "Clicker",
            ["Multi-Point"] = "Multipunto",
            ["Macros"] = "Macro",
            ["Statistics"] = "Statistiche",
            ["Keybinds"] = "Scorciatoie",
            ["Settings"] = "Impostazioni",
            ["Click Interval"] = "Intervallo di clic",
            ["Hours"] = "Ore", ["Minutes"] = "Minuti", ["Seconds"] = "Secondi", ["Millis"] = "Millis",
            ["Total delay between clicks. Minimum 1 ms."] = "Ritardo totale tra i clic. Minimo 1 ms.",
            ["Click Options"] = "Opzioni di clic",
            ["Button"] = "Pulsante", ["Type"] = "Tipo", ["Mode"] = "Modalità",
            ["Click Position"] = "Posizione del clic",
            ["Current cursor position"] = "Posizione attuale del cursore",
            ["Fixed position"] = "Posizione fissa",
            ["Multi-point (see Multi-Point tab)"] = "Multipunto (vedi scheda Multipunto)",
            ["Restore cursor position when stopped"] = "Ripristina la posizione del cursore all'arresto",
            ["Repeat"] = "Ripeti",
            ["Until stopped"] = "Fino all'arresto", ["Fixed count:"] = "Numero fisso:", ["For (seconds):"] = "Per (secondi):",
            ["Burst Settings"] = "Impostazioni raffica", ["Clicks per burst"] = "Clic per raffica", ["Pause (ms)"] = "Pausa (ms)",
            ["Randomization (anti-pattern)"] = "Randomizzazione (anti-pattern)",
            ["Randomize interval  ±"] = "Randomizza intervallo  ±", ["Randomize position  ±"] = "Randomizza posizione  ±",
            ["Manual Speed"] = "Velocità manuale", ["Speed (10 = 1.0x)"] = "Velocità (10 = 1.0x)",
            ["Anti-Freeze Protection"] = "Protezione anti-blocco",
            ["Enabled (prevents system freeze)"] = "Attivato (previene il blocco del sistema)",
            ["Max CPS"] = "CPS max", ["CPU %"] = "CPU %", ["CPS Test"] = "Test CPS",
            ["Pick…"] = "Scegli…", ["Profile:"] = "Profilo:",
            ["New"] = "Nuovo", ["Save"] = "Salva",
            ["Quick Capture"] = "Cattura rapida", ["Add…"] = "Aggiungi…", ["Edit…"] = "Modifica…",
            ["Remove"] = "Rimuovi", ["Show on screen"] = "Mostra a schermo", ["Order:"] = "Ordine:",
            ["Name:"] = "Nome:", ["X"] = "X", ["Y"] = "Y",
            ["Saved macros"] = "Macro salvate", ["Rename…"] = "Rinomina…", ["Duplicate"] = "Duplica",
            ["Move Up"] = "Sposta su", ["Move Down"] = "Sposta giù", ["Export…"] = "Esporta…", ["Import…"] = "Importa…",
            ["Delete"] = "Elimina", ["Notes…"] = "Note…", ["Export all…"] = "Esporta tutto…",
            ["Import all…"] = "Importa tutto…", ["Merge"] = "Unisci", ["Merge…"] = "Unisci…",
            ["Record"] = "Registra", ["● Record"] = "● Registra", ["Playback"] = "Riproduzione",
            ["Loops (0 = infinite)"] = "Cicli (0 = infinito)",
            ["Countdown (s, 0 = off)"] = "Conto alla rovescia (s, 0 = off)", ["Loop delay (ms)"] = "Ritardo tra cicli (ms)",
            ["▶ Play"] = "▶ Riproduci", ["Once"] = "Una volta", ["■ Stop"] = "■ Ferma",
            ["Smooth mouse movement"] = "Movimento fluido del mouse", ["Ready."] = "Pronto.",
            ["Live Monitor"] = "Monitor live", ["Append to selected macro"] = "Aggiungi alla macro selezionata",
            ["Capture keyboard"] = "Cattura tastiera", ["Capture mouse movement"] = "Cattura movimento del mouse",
            ["Not recording."] = "Nessuna registrazione.", ["Clear All"] = "Cancella tutto",
            ["Select, record, or play a macro to see steps here."] = "Seleziona, registra o riproduci una macro per vedere i passaggi qui.",
            ["Live Dashboard"] = "Dashboard live", ["Lifetime"] = "Totale", ["Records"] = "Record",
            ["Clicks by button"] = "Clic per pulsante",
            ["Session goal (clicks, 0 = off):"] = "Obiettivo sessione (clic, 0 = off):",
            ["Recent sessions (double-click for details, right-click for options)"] = "Sessioni recenti (doppio clic per dettagli, clic destro per opzioni)",
            ["Export CSV…"] = "Esporta CSV…", ["Reset session"] = "Reimposta sessione",
            ["Reset lifetime"] = "Reimposta totale", ["Clear history"] = "Cancella cronologia",
            ["Action"] = "Azione", ["Hotkey"] = "Tasto", ["Toggle On/Off"] = "Attiva/Disattiva",
            ["Save Keybinds"] = "Salva scorciatoie",
            ["Appearance"] = "Aspetto", ["Theme"] = "Tema", ["Always on top"] = "Sempre in primo piano",
            ["Language"] = "Lingua", ["Use a custom accent colour"] = "Usa un colore d'accento personalizzato",
            ["Choose colour…"] = "Scegli colore…", ["Preview"] = "Anteprima",
            ["Startup & Window"] = "Avvio e finestra",
            ["Launch Tempo when I sign in to Windows"] = "Avvia Tempo all'accesso a Windows",
            ["Hide window to tray when clicking starts"] = "Nascondi la finestra nella barra all'avvio dei clic",
            ["Hotkeys are configured on the Keybinds tab."] = "Le scorciatoie si configurano nella scheda Scorciatoie.",
            ["Behaviour"] = "Comportamento",
            ["Minimise to tray instead of closing"] = "Riduci nella barra invece di chiudere",
            ["Start minimised to tray"] = "Avvia ridotto nella barra",
            ["Show tray notifications"] = "Mostra notifiche della barra",
            ["Confirm before exit while running"] = "Conferma prima di uscire durante l'esecuzione",
            ["Allow Escape key as emergency stop"] = "Consenti Esc come arresto d'emergenza",
            ["Check for updates when Tempo starts"] = "Controlla aggiornamenti all'avvio di Tempo",
            ["Start delay before clicking (s):"] = "Ritardo iniziale prima dei clic (s):",
            ["Interval step (ms) for increase/decrease:"] = "Passo intervallo (ms) per aumenta/diminuisci:",
            ["Data & Backup"] = "Dati e backup", ["Open data folder"] = "Apri cartella dati",
            ["Open log file"] = "Apri file di log", ["Export settings…"] = "Esporta impostazioni…",
            ["Import settings…"] = "Importa impostazioni…", ["Uninstall Tempo…"] = "Disinstalla Tempo…",
            ["Check for updates"] = "Controlla aggiornamenti", ["About…"] = "Informazioni…",
            ["Reset to defaults"] = "Ripristina predefiniti", ["Save Settings"] = "Salva impostazioni",
            ["▶  Start"] = "▶  Avvia", ["■  Stop"] = "■  Ferma",
            ["Copy summary"] = "Copia riepilogo", ["Report a bug…"] = "Segnala un bug…", ["Email a bug…"] = "Invia un bug via email…",
            ["Running"] = "In esecuzione", ["Idle"] = "Inattivo", ["Paused"] = "In pausa",
            ["RUNNING"] = "IN ESECUZIONE", ["IDLE"] = "INATTIVO", ["PAUSED"] = "IN PAUSA",
            ["Playing macro"] = "Riproduzione macro", ["Recording macro"] = "Registrazione macro",
            ["Stopped (emergency)"] = "Fermato (emergenza)",
            ["Playing…"] = "Riproduzione…", ["Playback cancelled."] = "Riproduzione annullata.",
            ["Nothing was recorded."] = "Niente è stato registrato.",
            ["Est. total: ∞ (looping)"] = "Totale stim.: ∞ (in ciclo)", ["Est. total: ~"] = "Totale stim.: ~",
            ["Recording… bind/press the Record or Emergency-stop hotkey to finish."] = "Registrazione… premi il tasto Registra o Arresto d'emergenza per terminare.",
            ["Session goal reached"] = "Obiettivo sessione raggiunto", ["Checking…"] = "Controllo…",
            ["Detection: off — no rate limit"] = "Rilevamento: off — nessun limite",
            ["Profile: "] = "Profilo: ", ["Profile  •  "] = "Profilo  •  ",

            // --- Statistics tab (added 1.0.97) ---
            ["Session Clicks"] = "Clic sessione",
            ["Total (Launch)"] = "Totale (avvio)",
            ["Current CPS"] = "CPS attuali",
            ["Peak CPS"] = "CPS di picco",
            ["Average CPS"] = "CPS medi",
            ["Clicks / Min"] = "Clic / min",
            ["Elapsed"] = "Trascorso",
            ["Today"] = "Oggi",
            ["Left"] = "Sinistro",
            ["Right"] = "Destro",
            ["Middle"] = "Centrale",
            ["Lifetime Clicks"] = "Clic totali",
            ["Sessions"] = "Sessioni",
            ["Best CPS Ever"] = "Miglior CPS di sempre",
            ["Total Runtime"] = "Tempo totale",
            ["Most Clicks / Run"] = "Max clic / esec.",
            ["Longest Run"] = "Esecuzione più lunga",
            ["Avg Clicks / Session"] = "Clic medi / sessione",
            ["Avg Run Length"] = "Durata media",
            ["This Week"] = "Questa settimana",
            ["This Month"] = "Questo mese",
            ["This Year"] = "Quest'anno",
            ["Lifetime Avg CPS"] = "CPS medio totale",
            ["Active Days"] = "Giorni attivi",
            ["Best Day"] = "Giorno migliore",
            ["Busiest Weekday"] = "Giorno più attivo",
            ["Busiest Hour"] = "Ora più attiva",
            ["Top Profile"] = "Profilo principale",
            ["Current Streak"] = "Serie attuale",
            ["Longest Streak"] = "Serie più lunga",
            ["Daily Average"] = "Media giornaliera",
            ["Insights"] = "Approfondimenti",
            ["Unlock max speed (advanced)"] = "Sblocca velocità massima (avanzato)",
            ["day"] = "giorno",
            ["days"] = "giorni",
            // --- Charts / status bar (1.0.98) ---
            ["Clicks per recent session"] = "Clic per sessione recente",
            ["Clicks — last 7 days"] = "Clic — ultimi 7 giorni",
            ["Clicks by hour of day"] = "Clic per ora del giorno",
            ["Clicks by day of week"] = "Clic per giorno della settimana",
            ["Last 7 days · {0} clicks · peak {1}"] = "Ultimi 7 giorni · {0} clic · picco {1}",
            ["Loop"] = "Ciclo",
            ["step"] = "passo",
            ["Clicks:"] = "Clic:",
            ["CPS:"] = "CPS:",
            ["Time:"] = "Tempo:",
        };

        private static readonly Dictionary<string, string> Pt = new Dictionary<string, string>
        {
            ["Clicker"] = "Clicker",
            ["Multi-Point"] = "Multiponto",
            ["Macros"] = "Macros",
            ["Statistics"] = "Estatísticas",
            ["Keybinds"] = "Atalhos",
            ["Settings"] = "Configurações",
            ["Click Interval"] = "Intervalo de clique",
            ["Hours"] = "Horas", ["Minutes"] = "Minutos", ["Seconds"] = "Segundos", ["Millis"] = "Milis",
            ["Total delay between clicks. Minimum 1 ms."] = "Atraso total entre cliques. Mínimo 1 ms.",
            ["Click Options"] = "Opções de clique",
            ["Button"] = "Botão", ["Type"] = "Tipo", ["Mode"] = "Modo",
            ["Click Position"] = "Posição do clique",
            ["Current cursor position"] = "Posição atual do cursor",
            ["Fixed position"] = "Posição fixa",
            ["Multi-point (see Multi-Point tab)"] = "Multiponto (ver aba Multiponto)",
            ["Restore cursor position when stopped"] = "Restaurar a posição do cursor ao parar",
            ["Repeat"] = "Repetir",
            ["Until stopped"] = "Até parar", ["Fixed count:"] = "Quantidade fixa:", ["For (seconds):"] = "Por (segundos):",
            ["Burst Settings"] = "Configurações de rajada", ["Clicks per burst"] = "Cliques por rajada", ["Pause (ms)"] = "Pausa (ms)",
            ["Randomization (anti-pattern)"] = "Aleatorização (anti-padrão)",
            ["Randomize interval  ±"] = "Aleatorizar intervalo  ±", ["Randomize position  ±"] = "Aleatorizar posição  ±",
            ["Manual Speed"] = "Velocidade manual", ["Speed (10 = 1.0x)"] = "Velocidade (10 = 1.0x)",
            ["Anti-Freeze Protection"] = "Proteção anti-travamento",
            ["Enabled (prevents system freeze)"] = "Ativado (evita o travamento do sistema)",
            ["Max CPS"] = "CPS máx.", ["CPU %"] = "CPU %", ["CPS Test"] = "Teste de CPS",
            ["Pick…"] = "Escolher…", ["Profile:"] = "Perfil:",
            ["New"] = "Novo", ["Save"] = "Salvar",
            ["Quick Capture"] = "Captura rápida", ["Add…"] = "Adicionar…", ["Edit…"] = "Editar…",
            ["Remove"] = "Remover", ["Show on screen"] = "Mostrar na tela", ["Order:"] = "Ordem:",
            ["Name:"] = "Nome:", ["X"] = "X", ["Y"] = "Y",
            ["Saved macros"] = "Macros salvas", ["Rename…"] = "Renomear…", ["Duplicate"] = "Duplicar",
            ["Move Up"] = "Mover para cima", ["Move Down"] = "Mover para baixo", ["Export…"] = "Exportar…", ["Import…"] = "Importar…",
            ["Delete"] = "Excluir", ["Notes…"] = "Notas…", ["Export all…"] = "Exportar tudo…",
            ["Import all…"] = "Importar tudo…", ["Merge"] = "Mesclar", ["Merge…"] = "Mesclar…",
            ["Record"] = "Gravar", ["● Record"] = "● Gravar", ["Playback"] = "Reprodução",
            ["Loops (0 = infinite)"] = "Repetições (0 = infinito)",
            ["Countdown (s, 0 = off)"] = "Contagem regressiva (s, 0 = off)", ["Loop delay (ms)"] = "Atraso entre repetições (ms)",
            ["▶ Play"] = "▶ Reproduzir", ["Once"] = "Uma vez", ["■ Stop"] = "■ Parar",
            ["Smooth mouse movement"] = "Movimento suave do mouse", ["Ready."] = "Pronto.",
            ["Live Monitor"] = "Monitor ao vivo", ["Append to selected macro"] = "Anexar à macro selecionada",
            ["Capture keyboard"] = "Capturar teclado", ["Capture mouse movement"] = "Capturar movimento do mouse",
            ["Not recording."] = "Sem gravação.", ["Clear All"] = "Limpar tudo",
            ["Select, record, or play a macro to see steps here."] = "Selecione, grave ou reproduza uma macro para ver os passos aqui.",
            ["Live Dashboard"] = "Painel ao vivo", ["Lifetime"] = "Total", ["Records"] = "Recordes",
            ["Clicks by button"] = "Cliques por botão",
            ["Session goal (clicks, 0 = off):"] = "Meta da sessão (cliques, 0 = off):",
            ["Recent sessions (double-click for details, right-click for options)"] = "Sessões recentes (clique duplo para detalhes, clique direito para opções)",
            ["Export CSV…"] = "Exportar CSV…", ["Reset session"] = "Redefinir sessão",
            ["Reset lifetime"] = "Redefinir total", ["Clear history"] = "Limpar histórico",
            ["Action"] = "Ação", ["Hotkey"] = "Tecla", ["Toggle On/Off"] = "Ligar/Desligar",
            ["Save Keybinds"] = "Salvar atalhos",
            ["Appearance"] = "Aparência", ["Theme"] = "Tema", ["Always on top"] = "Sempre no topo",
            ["Language"] = "Idioma", ["Use a custom accent colour"] = "Usar cor de destaque personalizada",
            ["Choose colour…"] = "Escolher cor…", ["Preview"] = "Pré-visualização",
            ["Startup & Window"] = "Inicialização e janela",
            ["Launch Tempo when I sign in to Windows"] = "Iniciar o Tempo ao entrar no Windows",
            ["Hide window to tray when clicking starts"] = "Ocultar a janela na bandeja ao iniciar os cliques",
            ["Hotkeys are configured on the Keybinds tab."] = "Os atalhos são configurados na aba Atalhos.",
            ["Behaviour"] = "Comportamento",
            ["Minimise to tray instead of closing"] = "Minimizar para a bandeja em vez de fechar",
            ["Start minimised to tray"] = "Iniciar minimizado na bandeja",
            ["Show tray notifications"] = "Mostrar notificações da bandeja",
            ["Confirm before exit while running"] = "Confirmar antes de sair durante a execução",
            ["Allow Escape key as emergency stop"] = "Permitir Esc como parada de emergência",
            ["Check for updates when Tempo starts"] = "Verificar atualizações ao iniciar o Tempo",
            ["Start delay before clicking (s):"] = "Atraso inicial antes de clicar (s):",
            ["Interval step (ms) for increase/decrease:"] = "Passo do intervalo (ms) para aumentar/diminuir:",
            ["Data & Backup"] = "Dados e backup", ["Open data folder"] = "Abrir pasta de dados",
            ["Open log file"] = "Abrir arquivo de log", ["Export settings…"] = "Exportar configurações…",
            ["Import settings…"] = "Importar configurações…", ["Uninstall Tempo…"] = "Desinstalar o Tempo…",
            ["Check for updates"] = "Verificar atualizações", ["About…"] = "Sobre…",
            ["Reset to defaults"] = "Restaurar padrões", ["Save Settings"] = "Salvar configurações",
            ["▶  Start"] = "▶  Iniciar", ["■  Stop"] = "■  Parar",
            ["Copy summary"] = "Copiar resumo", ["Report a bug…"] = "Relatar um erro…", ["Email a bug…"] = "Enviar erro por e-mail…",
            ["Running"] = "Em execução", ["Idle"] = "Inativo", ["Paused"] = "Pausado",
            ["RUNNING"] = "EM EXECUÇÃO", ["IDLE"] = "INATIVO", ["PAUSED"] = "PAUSADO",
            ["Playing macro"] = "Reproduzindo macro", ["Recording macro"] = "Gravando macro",
            ["Stopped (emergency)"] = "Parado (emergência)",
            ["Playing…"] = "Reproduzindo…", ["Playback cancelled."] = "Reprodução cancelada.",
            ["Nothing was recorded."] = "Nada foi gravado.",
            ["Est. total: ∞ (looping)"] = "Total est.: ∞ (em ciclo)", ["Est. total: ~"] = "Total est.: ~",
            ["Recording… bind/press the Record or Emergency-stop hotkey to finish."] = "Gravando… pressione a tecla Gravar ou Parada de emergência para terminar.",
            ["Session goal reached"] = "Meta da sessão atingida", ["Checking…"] = "Verificando…",
            ["Detection: off — no rate limit"] = "Detecção: desligada — sem limite",
            ["Profile: "] = "Perfil: ", ["Profile  •  "] = "Perfil  •  ",

            // --- Statistics tab (added 1.0.97) ---
            ["Session Clicks"] = "Cliques da sessão",
            ["Total (Launch)"] = "Total (início)",
            ["Current CPS"] = "CPS atual",
            ["Peak CPS"] = "CPS de pico",
            ["Average CPS"] = "CPS médio",
            ["Clicks / Min"] = "Cliques / min",
            ["Elapsed"] = "Decorrido",
            ["Today"] = "Hoje",
            ["Left"] = "Esquerdo",
            ["Right"] = "Direito",
            ["Middle"] = "Meio",
            ["Lifetime Clicks"] = "Cliques totais",
            ["Sessions"] = "Sessões",
            ["Best CPS Ever"] = "Melhor CPS de sempre",
            ["Total Runtime"] = "Tempo total",
            ["Most Clicks / Run"] = "Máx. cliques / exec.",
            ["Longest Run"] = "Execução mais longa",
            ["Avg Clicks / Session"] = "Cliques méd. / sessão",
            ["Avg Run Length"] = "Duração média",
            ["This Week"] = "Esta semana",
            ["This Month"] = "Este mês",
            ["This Year"] = "Este ano",
            ["Lifetime Avg CPS"] = "CPS médio total",
            ["Active Days"] = "Dias ativos",
            ["Best Day"] = "Melhor dia",
            ["Busiest Weekday"] = "Dia mais ativo",
            ["Busiest Hour"] = "Hora mais ativa",
            ["Top Profile"] = "Perfil principal",
            ["Current Streak"] = "Sequência atual",
            ["Longest Streak"] = "Maior sequência",
            ["Daily Average"] = "Média diária",
            ["Insights"] = "Análises",
            ["Unlock max speed (advanced)"] = "Desbloquear velocidade máxima (avançado)",
            ["day"] = "dia",
            ["days"] = "dias",
            // --- Charts / status bar (1.0.98) ---
            ["Clicks per recent session"] = "Cliques por sessão recente",
            ["Clicks — last 7 days"] = "Cliques — últimos 7 dias",
            ["Clicks by hour of day"] = "Cliques por hora do dia",
            ["Clicks by day of week"] = "Cliques por dia da semana",
            ["Last 7 days · {0} clicks · peak {1}"] = "Últimos 7 dias · {0} cliques · pico {1}",
            ["Loop"] = "Ciclo",
            ["step"] = "passo",
            ["Clicks:"] = "Cliques:",
            ["CPS:"] = "CPS:",
            ["Time:"] = "Tempo:",
        };
    }
}
