<#
  stamp-build.ps1 — stamps a fresh build ID into Utils\BuildInfo.Generated.cs.

  publish.cmd runs this immediately before every build, so the build ID moves on every
  publish while the version number stays put. That is the whole point: a test build and
  the release it was cut from carry the SAME version, and without a build ID there is
  nothing on screen to tell them apart.

  THE ID IS THE BUILD TIME, to the minute, in UTC ("260902-2112"). It used to be a
  counter, which read more nicely ("build 5") but had to be stored somewhere — and once
  the generated file became git-ignored, that store lived in exactly one working tree. A
  fresh clone restarted at 1 and two different builds could both claim to be build 5. A
  timestamp needs no store and sorts into build order by itself.

  Minutes, not seconds, because the ID is meant to be read aloud. Two publishes inside
  one minute would then collide, so this compares against the stamp already in the file
  and waits out the rest of the minute rather than issue a duplicate.

    .\stamp-build.ps1                  -> stamp now, channel "test"
    .\stamp-build.ps1 -Channel release -> stamp now, channel "release"
    .\stamp-build.ps1 -DryRun          -> report what it would do, write nothing

  Prints the new build ID on stdout (publish.cmd captures it).

  ASSERT-FIRST: both constants must match exactly once each, or the file is left
  completely untouched and the script exits non-zero. A half-stamped BuildInfo would be
  worse than none, because it would lie with confidence.
#>
[CmdletBinding()]
param(
    [ValidateSet('test', 'release')]
    [string] $Channel = 'test',

    [string] $Path,

    [switch] $DryRun
)

$ErrorActionPreference = 'Stop'

# Resolved HERE, not as a param default: $PSScriptRoot is empty while the param block is
# being bound under "powershell -File", so the default silently became Join-Path '' -> a
# binding error and no stamp at all. publish.cmd sends stderr to nul, so it showed up
# only as "build ID was not stamped".
if (-not $Path) {
    $root = $PSScriptRoot
    if (-not $root) { $root = Split-Path -Parent $MyInvocation.MyCommand.Path }
    $Path = Join-Path $root 'Utils\BuildInfo.Generated.cs'
}

$header = @'
// GENERATED by stamp-build.ps1 — do not hand-edit, and do not commit.
// This file is git-ignored: it changes on every publish. The logic that reads these
// constants is the other half of the partial class, in BuildInfo.cs.
namespace AutoClicker.Utils
{
    public static partial class BuildInfo
    {
        public const string StampUtc = "";
        public const string Channel = "dev";
    }
}
'@

# The generated half is git-ignored, so a fresh clone does not have it. Seed it rather
# than fail: the csproj's EnsureBuildInfo target writes the same content, but publish
# must not depend on a build having run first.
if (-not (Test-Path -LiteralPath $Path)) {
    Write-Host "seeding $Path (was missing)"
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllText($Path, $header, (New-Object System.Text.UTF8Encoding $true))
}

$text = [System.IO.File]::ReadAllText($Path)

# One regex per constant. Captured groups keep the exact surrounding text, so
# indentation and line endings survive untouched.
$reStamp   = '(?m)^(?<a>\s*public const string StampUtc = ")(?<v>[^"]*)(?<b>";)'
$reChannel = '(?m)^(?<a>\s*public const string Channel = ")(?<v>[^"]*)(?<b>";)'

foreach ($pair in @(@($reStamp, 'StampUtc'), @($reChannel, 'Channel'))) {
    $n = ([regex]::Matches($text, $pair[0])).Count
    if ($n -ne 1) {
        Write-Error "BuildInfo.Generated.cs: '$($pair[1])' matched $n times (expected exactly 1). Nothing written."
        exit 2
    }
}

# The ID is only precise to the MINUTE, because it has to be readable. So a second
# publish inside the same minute would hand out an ID that already exists. The previous
# stamp is right there in the file, so compare against it and wait out the remainder of
# the minute rather than issue a duplicate. Costs at most 59s, only on a rapid
# re-publish, and keeps "the ID never repeats" actually true.
$now  = [DateTime]::UtcNow
$prev = [regex]::Match($text, $reStamp).Groups['v'].Value
if ($prev) {
    $prevT = [DateTime]::MinValue
    if ([DateTime]::TryParse($prev, [ref] $prevT)) {
        $prevT = $prevT.ToUniversalTime()
        if ($prevT.ToString('yyMMdd-HHmm') -eq $now.ToString('yyMMdd-HHmm')) {
            $wait = 60 - $now.Second
            if ($DryRun) {
                Write-Host "would wait ${wait}s: same minute as the last build ($prev)"
            }
            else {
                Write-Host "same minute as the last build - waiting ${wait}s so the ID stays unique"
                Start-Sleep -Seconds $wait
                $now = [DateTime]::UtcNow
            }
        }
    }
}

$stamp = $now.ToString('yyyy-MM-ddTHH:mm:ssZ')
$id    = $now.ToString('yyMMdd-HHmm')

if ($DryRun) {
    Write-Host "would stamp: build $id, channel $Channel"
    exit 0
}

$text = [regex]::Replace($text, $reStamp,   { param($m) $m.Groups['a'].Value + $stamp   + $m.Groups['b'].Value })
$text = [regex]::Replace($text, $reChannel, { param($m) $m.Groups['a'].Value + $Channel + $m.Groups['b'].Value })

# UTF-8 WITH BOM, written through .NET rather than Set-Content: PowerShell 5.1's cmdlets
# default to the ANSI codepage and would mangle the em dash in the header comment. The
# rest of the project's .cs files carry a BOM too.
[System.IO.File]::WriteAllText($Path, $text, (New-Object System.Text.UTF8Encoding $true))

# ── developer build history ──────────────────────────────────────────────────
#
# One line per build, appended forever. This is a DEVELOPER record and nothing in
# the app reads it: it answers "when did I make 260902-2123, and was it a release?"
# and "which build did I hand to someone last Tuesday?" -- questions the shipped
# app has no way to answer, because a build only knows about itself.
#
# Lives under bin\ so it is git-ignored along with everything else there, and it
# survives publish.cmd's clean, which removes bin\publish\<rid>, obj and
# bin\Release but not bin\ itself. publish.cmd appends the exe hash and size to
# the same row once the build has actually produced one.
try {
    $histDir = Join-Path (Split-Path -Parent $Path) '..'
    $histDir = Join-Path (Resolve-Path $histDir).Path 'bin'
    if (-not (Test-Path -LiteralPath $histDir)) {
        New-Item -ItemType Directory -Path $histDir -Force | Out-Null
    }
    $hist = Join-Path $histDir 'build-history.tsv'
    if (-not (Test-Path -LiteralPath $hist)) {
        Set-Content -LiteralPath $hist -Encoding utf8 `
            -Value "stamped_utc`tbuild_id`tchannel`tversion`tsha256`tbytes"
    }

    # The version comes from the csproj, so the row says what this build IS rather
    # than what the tooling assumed.
    $ver = ''
    $csproj = Join-Path (Split-Path -Parent (Split-Path -Parent $Path)) 'AutoClicker.csproj'
    if (Test-Path -LiteralPath $csproj) {
        $m = Select-String -LiteralPath $csproj -Pattern '<Version>([^<]+)</Version>' | Select-Object -First 1
        if ($m) { $ver = $m.Matches[0].Groups[1].Value }
    }

    Add-Content -LiteralPath $hist -Encoding utf8 `
        -Value ("{0}`t{1}`t{2}`t{3}`t`t" -f $stamp, $id, $Channel, $ver)
}
catch {
    # A history line is a convenience, never a reason to fail a build.
    Write-Host "note: could not append to build-history.tsv ($_)"
}

# stdout is the contract with publish.cmd — the ID, alone, nothing else.
Write-Output $id
