using System;
using System.Globalization;

namespace AutoClicker.Utils
{
    /// <summary>
    /// Identifies THIS build, independently of the version number.
    ///
    /// The version says nothing about which build you are actually running. Every test
    /// build carries the same 1.0.319 as the release it was cut from, so a test copy and
    /// the published release look identical everywhere the version is printed — the exact
    /// confusion this exists to end. The BUILD NUMBER moves on every publish; the VERSION
    /// only moves when a real release does. When the two disagree about what you are
    /// looking at, believe the build number.
    ///
    /// This half is the logic, and it lives in git. The three constants it reads —
    /// <c>Number</c>, <c>StampUtc</c> and <c>Channel</c> — are in the OTHER half,
    /// BuildInfo.Generated.cs, which is generated by stamp-build.ps1 and git-ignored:
    /// it changes on every publish, and a file that churns on every build has no place
    /// in history.
    ///
    /// If that file is missing — a fresh clone — the EnsureBuildInfo target in the
    /// csproj writes a neutral one before the compiler runs, so the project always
    /// builds. It comes out as build 0, which reports as "unstamped dev build": true,
    /// and better than a number that would be a lie.
    /// </summary>
    public static partial class BuildInfo
    {
        /// <summary>An official release build — the artifact that goes on GitHub.</summary>
        public static bool IsRelease
        {
            get { return string.Equals(Channel, "release", StringComparison.OrdinalIgnoreCase); }
        }

        /// <summary>A build that was never stamped: someone ran dotnet build, not publish.</summary>
        public static bool IsUnstamped
        {
            get { return Number <= 0; }
        }

        /// <summary>True for anything that is not an official release.</summary>
        public static bool IsTest
        {
            get { return !IsRelease; }
        }

        /// <summary>
        /// The badge that marks a build you should not mistake for the real thing:
        /// "TEST", "DEV", or empty for an official release.
        /// </summary>
        public static string Badge
        {
            get
            {
                if (IsUnstamped) { return "DEV"; }
                return IsRelease ? "" : "TEST";
            }
        }

        /// <summary>
        /// Short form for the places a version already appears — "build 48",
        /// "build 48 · TEST", or "unstamped dev build".
        /// </summary>
        public static string Short
        {
            get
            {
                if (IsUnstamped) { return "unstamped dev build"; }
                string s = "build " + Number.ToString(CultureInfo.InvariantCulture);
                string badge = Badge;
                return badge.Length == 0 ? s : s + " · " + badge;
            }
        }

        /// <summary>Short form plus when it was built — for About, the log and bug reports.</summary>
        public static string Full
        {
            get
            {
                string when = BuiltUtcText;
                return when.Length == 0 ? Short : Short + " · built " + when;
            }
        }

        /// <summary>Build time as "2026-09-02 16:21 UTC", or empty if it was never stamped.</summary>
        public static string BuiltUtcText
        {
            get
            {
                DateTime t;
                if (!string.IsNullOrEmpty(StampUtc)
                    && DateTime.TryParse(StampUtc, CultureInfo.InvariantCulture,
                        DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out t))
                {
                    return t.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) + " UTC";
                }
                return "";
            }
        }
    }
}
