using System;
using System.Globalization;

namespace AutoClicker.Utils
{
    /// <summary>
    /// Identifies THIS build, independently of the version number.
    ///
    /// The version says nothing about which build you are actually running. Every test
    /// build carries the same 1.0.319 as the release it was cut from, so a test copy and
    /// the published release look identical everywhere the version is printed — the exact
    /// confusion this exists to end. The BUILD NUMBER moves on every publish; the VERSION
    /// only moves when a real release does. When the two disagree about what you are
    /// looking at, believe the build number.
    ///
    /// THE THREE CONSTANTS BELOW ARE GENERATED by stamp-build.ps1, which publish.cmd runs
    /// before every build. Do not hand-edit them — the next publish overwrites them. Do
    /// commit the result, so the number that shipped is recorded in git.
    /// </summary>
    public static class BuildInfo
    {
        // ─── generated by stamp-build.ps1 — do not hand-edit ───────────────────
        public const int Number = 5;
        public const string StampUtc = "2026-09-02T20:45:34Z";
        public const string Channel = "test";
        // ─── end generated ─────────────────────────────────────────────────────

        /// <summary>An official release build — the artifact that goes on GitHub.</summary>
        public static bool IsRelease
        {
            get { return string.Equals(Channel, "release", StringComparison.OrdinalIgnoreCase); }
        }

        /// <summary>A build that was never stamped: someone ran dotnet build, not publish.</summary>
        public static bool IsUnstamped
        {
            get { return Number <= 0; }
        }

        /// <summary>True for anything that is not an official release.</summary>
        public static bool IsTest
        {
            get { return !IsRelease; }
        }

        /// <summary>
        /// The badge that marks a build you should not mistake for the real thing:
        /// "TEST", "DEV", or empty for an official release.
        /// </summary>
        public static string Badge
        {
            get
            {
                if (IsUnstamped) { return "DEV"; }
                return IsRelease ? "" : "TEST";
            }
        }

        /// <summary>
        /// Short form for the places a version already appears — "build 48",
        /// "build 48 · TEST", or "unstamped dev build".
        /// </summary>
        public static string Short
        {
            get
            {
                if (IsUnstamped) { return "unstamped dev build"; }
                string s = "build " + Number.ToString(CultureInfo.InvariantCulture);
                string badge = Badge;
                return badge.Length == 0 ? s : s + " · " + badge;
            }
        }

        /// <summary>Short form plus when it was built — for About, the log and bug reports.</summary>
        public static string Full
        {
            get
            {
                string when = BuiltUtcText;
                return when.Length == 0 ? Short : Short + " · built " + when;
            }
        }

        /// <summary>Build time as "2026-09-02 16:21 UTC", or empty if it was never stamped.</summary>
        public static string BuiltUtcText
        {
            get
            {
                DateTime t;
                if (!string.IsNullOrEmpty(StampUtc)
                    && DateTime.TryParse(StampUtc, CultureInfo.InvariantCulture,
                        DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out t))
                {
                    return t.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) + " UTC";
                }
                return "";
            }
        }
    }
}
