using System;
using System.Globalization;

namespace AutoClicker.Utils
{
    /// <summary>
    /// Identifies THIS build, independently of the version number.
    ///
    /// The version says nothing about which build you are actually running. Every test
    /// build carries the same 1.0.319 as the release it was cut from, so a test copy and
    /// the published release look identical everywhere the version is printed — the exact
    /// confusion this exists to end. The BUILD ID moves on every publish; the VERSION
    /// only moves when a real release does. When the two disagree about what you are
    /// looking at, believe the build ID.
    ///
    /// THE ID IS THE BUILD TIME, to the minute, in UTC — "260902-2112". It was a
    /// counter, which read more nicely ("build 5") but had to be stored somewhere, and
    /// once the generated file became git-ignored that store lived only in one working
    /// tree: a fresh clone restarted at 1 and two different builds could both claim to
    /// be build 5. A timestamp needs no store, cannot repeat, and sorts into build order
    /// on its own.
    ///
    /// Minutes, not seconds, because the ID is meant to be read aloud and typed into a
    /// bug report. Two publishes inside one minute would therefore collide — so
    /// stamp-build.ps1 compares against the stamp already in the file and waits out the
    /// remainder of the minute rather than issue the same ID twice. StampUtc itself
    /// keeps full second precision; only the ID is rounded.
    ///
    /// This half is the logic, and it lives in git. The two constants it reads are in
    /// the other half, BuildInfo.Generated.cs, which is generated by stamp-build.ps1 and
    /// git-ignored. If that file is missing — a fresh clone — the EnsureBuildInfo target
    /// in the csproj writes a neutral one before the compiler runs, so the project always
    /// builds; it reports as "unstamped dev build", which is true and better than a
    /// number that would be a lie.
    /// </summary>
    public static partial class BuildInfo
    {
        /// <summary>An official release build — the artifact that goes on GitHub.</summary>
        public static bool IsRelease
        {
            get { return string.Equals(Channel, "release", StringComparison.OrdinalIgnoreCase); }
        }

        /// <summary>True for anything that is not an official release.</summary>
        public static bool IsTest
        {
            get { return !IsRelease; }
        }

        /// <summary>A build that was never stamped: someone ran dotnet build, not publish.</summary>
        public static bool IsUnstamped
        {
            get { return !BuiltUtc.HasValue; }
        }

        /// <summary>When this build was stamped, or null if it never was.</summary>
        public static DateTime? BuiltUtc
        {
            get
            {
                DateTime t;
                if (!string.IsNullOrEmpty(StampUtc)
                    && DateTime.TryParse(StampUtc, CultureInfo.InvariantCulture,
                        DateTimeStyles.AdjustToUniversal | DateTimeStyles.AssumeUniversal, out t))
                {
                    return t;
                }
                return null;
            }
        }

        /// <summary>
        /// The build ID itself: "260902-2112" — yyMMdd-HHmm in UTC. Short enough to read
        /// aloud and type into a bug report, and readable as a date once you know that
        /// is what it is. Uniqueness to the minute is enforced by stamp-build.ps1, which
        /// will not issue the same ID twice.
        /// </summary>
        public static string Id
        {
            get
            {
                DateTime? t = BuiltUtc;
                return t.HasValue
                    ? t.Value.ToString("yyMMdd-HHmm", CultureInfo.InvariantCulture)
                    : "";
            }
        }

        /// <summary>
        /// The badge that marks a build you should not mistake for the real thing:
        /// "TEST", "DEV", or empty for an official release.
        /// </summary>
        public static string Badge
        {
            get
            {
                if (IsUnstamped) { return "DEV"; }
                return IsRelease ? "" : "TEST";
            }
        }

        /// <summary>
        /// What every screen shows: "build 260902-205530 · TEST", or
        /// "unstamped dev build" when it was never published.
        /// </summary>
        public static string Short
        {
            get
            {
                if (IsUnstamped) { return "unstamped dev build"; }
                string s = "build " + Id;
                string badge = Badge;
                return badge.Length == 0 ? s : s + " · " + badge;
            }
        }

        /// <summary>
        /// Build time spelled out — "2026-09-02 20:55 UTC". The ID already encodes this,
        /// so it is only for the one place that has room to be unambiguous to a reader
        /// who does not know the ID's format: the About box.
        /// </summary>
        public static string BuiltUtcText
        {
            get
            {
                DateTime? t = BuiltUtc;
                return t.HasValue
                    ? t.Value.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) + " UTC"
                    : "";
            }
        }
    }
}
